### ISSUE TITLE
Integration not loading after Platform Migration 

### ISSUE THREAD

**Issue by BossLurker** [swartjean/ha-eskom-loadshedding#20]
HI Jean. 

I migrated from a vm installation to a pi 4 8gb Home assistant OS ...

I did a full backup and restore but Loadshedding integration is now not loading. 

I have tried deleting and reloading but I still get the integration not loaded message

2022-09-05 17:44:34.573 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.eskom_loadshedding
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 638, in get_component
cache[self.domain] = importlib.import_module(self.pkg_path)
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/eskom_loadshedding/__init__.py", line 15, in <module>
from .eskom_interface import eskom_interface
File "/config/custom_components/eskom_loadshedding/eskom_interface.py", line 4, in <module>
from aiohttp_retry import RetryClient
ValueError: source code string cannot contain null bytes
2022-09-05 17:44:34.577 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration eskom_loadshedding: Unable to import component: Exception importing custom_components.eskom_loadshedding

EDIT : WHen I try to reload it it says configuration not supported by UI

Sorry I am very new to HA ...

I am on version 1.0.6 of loadshedding....

I hope I have given enough information...

**Comment by BossLurker** [comment]
Hi 
I managed to get it working by doing a backup, reflash the sd and repeat the backup restore... 
Not sure what caused it but now everything is working....
