### ISSUE TITLE
Can't select area in Eskom Loadshedding

### ISSUE THREAD

**Issue by mmaritz115** [swartjean/ha-eskom-loadshedding#30]
## Configuration

```yaml

Add your logs here.

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/eskom_loadshedding/config_flow.py:64
Integration: Eskom Loadshedding Interface (documentation, issues)
First occurred: 7:05:13 AM (14 occurrences)
Last logged: 6:21:00 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/eskom_loadshedding/config_flow.py", line 64, in async_step_area_search
    self.area_list = areas["areas"]
KeyError: 'areas'

## Describe the bug
A clear and concise description of what the bug is.


## Debug log

<!-- To enable debug logs check this https://www.home-assistant.io/components/logger/ -->

After insert API key get error when select area

Add your logs here.

```

**Comment by swartjean** [comment]
Hi, unfortunately I can't replicate this on my side. I tested with a few HA versions and I am able to select areas without any issues.

A bit of googling shows that error popping up on a number of integrations with no real solutions. Which HA version are you on and can you try to update? Looks like it might be a SSL problem.

I'm tracking similar problems under #31 so let's shift the conversation there. Closing this one.
