### ISSUE TITLE
Adding Area "Unknown error occured"

### ISSUE THREAD

**Issue by JossPer0** [swartjean/ha-eskom-loadshedding#36]
Home Assistant 2023.5.4
Supervisor 2023.04.1
Frontend 20230503.3 - latest

This is similar to issue number 34, where I can't seem to add an area. It just bombs with the "unknown error" I checked the logs but I don't see anywhere it says "attempted abuse." I am fairly new to HA though so perhaps I am doing something wrong.

I had it working, but had needed to change my area as Durban is now on a new schedule. So deleted and installed again and now I have this issue.

![unknown error](https://github.com/swartjean/ha-eskom-loadshedding/assets/37881812/db505c21-9e00-43e9-9947-11fedf67e36e)

This error originated from a custom integration.

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/eskom_loadshedding/config_flow.py", line 64, in async_step_area_search
    self.area_list = areas["areas"]
KeyError: 'areas'

**Comment by ipodmusicman** [comment]
This happened to me as well and learnt based on the other issue that it is due to abuse.  Yeah, I decided to set the poll to be more frequent and ran out of API calls, so I created a new API key as I didn't want to wait until the next day and ESP saw this as abuse.  Ooops.   In order to fix this, just reboot your router so that your ISP assigns you a new IP address.  In my Unifi set up, I just downed and upped the eth on the CLI and all was good in the world and nobody in the house noticed. :)

**Comment by jraydoran** [comment]
I too am having this issue. I registered for a new API key and still get this issue. Only using it on 1 HA instance with no luck.

**Comment by jraydoran** [comment]
After spending way to much time fault-finding this issue, I tried the "Paid" version of API and all is well. I have no idea how I will be able to go back to the "Free" version.

**Comment by Dyltong** [comment]
I am having the same issue. API key is accepted then:

![image](https://github.com/swartjean/ha-eskom-loadshedding/assets/21261121/67cd325c-7dcb-4569-877a-d252d5a04637)

**Comment by Dyltong** [comment]
> This happened to me as well and learnt based on the other issue that it is due to abuse. Yeah, I decided to set the poll to be more frequent and ran out of API calls, so I created a new API key as I didn't want to wait until the next day and ESP saw this as abuse. Ooops. In order to fix this, just reboot your router so that your ISP assigns you a new IP address. In my Unifi set up, I just downed and upped the eth on the CLI and all was good in the world and nobody in the house noticed. :)

https://github.com/swartjean/ha-eskom-loadshedding/issues/36#issuecomment-1585701042

I did this and it worked, thanks @ipodmusicman 

I turned the fibre box and router on and off again, got the same ip, turned it off for 15 min, success.

**Comment by swartjean** [comment]
Hi all, closing this since the issues seem to be resolved. Please open a new issue if any strangeness persists.
